# Generated by Django 2.0.6 on 2018-12-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YogaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.RenameModel(
            old_name='SignUp',
            new_name='Contact',
        ),
    ]
