# Generated by Django 2.0.6 on 2018-12-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YogaApp', '0002_auto_20181216_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
